[package]
name = "digisafe"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
chacha20poly1305 = "0.10.1"
gdk = { version = "0.5.4", package = "gdk4", features = ["v4_8"] }
gtk = { version = "0.5.4", package = "gtk4", features = ["v4_8"] }
hex = "0.4.3"
reqwest = { version = "0.13.1", features = ["blocking"] }
rust-argon2 = "3.0.0"
serde_json = "1.0.91"
sha1 = "0.10.5"
sha2 = "0.10.6"
